[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect and rewrite rules for Next.js
[[redirects]]
  from = "/*"
  to = "/_netlify_html_rewriter_finished_rendering"
  status = 200
  force = false
  conditions = {Netlify-Html-Rewriter-Finished-Rendering = ""}

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Uncomment for SPA fallback
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
